apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-kali
  labels:
    app: capstone-kali
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: capstone-kali
  template:
    metadata:
      labels:
        app: capstone-kali
    spec:
      containers:
      - name: capstone-kali
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.env }}"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: capstone-kali-config
